#!/bin/sh

# Create bridge and add the physical ifs
brctl addbr br-shit
brctl addif br-shit eth0
brctl addif br-shit eth1

# Configure the bridge
ip link set br-shit up
ip link set eth0 up
ip link set eth1 up
ip addr add 114.5.14.1/24 dev br-shit


# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

